name:                aoc
version:             0.1.0.0
github:              "ChrisCoffey/aoc"
license:             MIT
author:              "Chris Coffey"
maintainer:          "chris@coffey.dev"
copyright:           "2021 Chris Coffey"

description:         Please see the README on GitHub at <https://github.com/ChrisCoffey/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- cryptonite
- hashable
- hashtables
- heap
- matrix
- mtl
- protolude
- psqueues
- text
- unordered-containers
- vector

default-extensions:
  MultiParamTypeClasses
  OverloadedStrings
  FlexibleContexts
  FlexibleInstances
  NamedFieldPuns
  TupleSections
  DeriveGeneric
  DeriveAnyClass
  GeneralizedNewtypeDeriving
  DerivingStrategies
  FunctionalDependencies
  TypeApplications
  UndecidableInstances
  GADTs
  ConstraintKinds
  NoImplicitPrelude
  ScopedTypeVariables

library:
  source-dirs: src

tests:
  aoc:
    main:                Spec.hs
    source-dirs:         spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-instances
    - QuickCheck
    - HUnit
